### ISSUE TITLE
I can`t install package.

### ISSUE THREAD

**Issue by artur-kardash** [agoalofalife/bpm-online#2]
When I write:
composer require agoalofalife/bpm-online
I get:
  Problem 1
    - Installation request for agoalofalife/bpm-online ^2.1 -> satisfiable by agoalofalife/bpm-online[2.1.0].
    - Conclusion: remove laravel/framework v5.5.39
    - Conclusion: don't install laravel/framework v5.5.39
    - agoalofalife/bpm-online 2.1.0 requires illuminate/config 5.4.* -> satisfiable by illuminate/config[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - don't install illuminate/config v5.4.0|don't install laravel/framework v5.5.39
    - don't install illuminate/config v5.4.13|don't install laravel/framework v5.5.39
    - don't install illuminate/config v5.4.17|don't install laravel/framework v5.5.39
    - don't install illuminate/config v5.4.19|don't install laravel/framework v5.5.39
    - don't install illuminate/config v5.4.27|don't install laravel/framework v5.5.39
    - don't install illuminate/config v5.4.36|don't install laravel/framework v5.5.39
    - don't install illuminate/config v5.4.9|don't install laravel/framework v5.5.39
    - Installation request for laravel/framework (locked at v5.5.39, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.39].

**Comment by agoalofalife** [comment]
@artur-kardash version Laravel ?

**Comment by artur-kardash** [comment]
Version 5.5.39

**Comment by artur-kardash** [comment]
Version 5.5.39

**Comment by agoalofalife** [comment]
in dependencies there are components laravel version v5.4.0
I think this is the reason
you can remove them yourself and make PR
or to wait when I have time I'll do it myself

**Comment by artur-kardash** [comment]
I'm not familiar with the library as I haven't used it. I hope for your help. Thank you.

**Comment by agoalofalife** [comment]
well then I'll let you know!)

**Comment by artur-kardash** [comment]
I'll be wait)
Thank you so much!

**Comment by agoalofalife** [comment]
@artur-kardash Hello!
I upgraded version to 2.1.2
Run command `composer require agoalofalife/bpm-online 2.1.2`
should do it.

**Comment by artur-kardash** [comment]
@agoalofalife Hey)
Yes, thank you. All is successfully installed.
