### ISSUE TITLE
CookieAuthentication.php:59 ob_clean(): failed to delete buffer

### ISSUE THREAD

**Issue by bunke** [agoalofalife/bpm-online#3]
Please fix this Notice:

PHP Notice 'yii\base\ErrorException' with message 'ob_clean(): failed to delete buffer. No buffer to delete'

in /var/www/bookimed/app/vendor/agoalofalife/bpm-online/src/Assistants/CookieAuthentication.php:59

**Comment by agoalofalife** [comment]
@bunke 
when you have time, I will fix it
you can send PR

**Comment by bunke** [comment]
https://github.com/agoalofalife/bpm-online/pull/4
