### ISSUE TITLE
How to get Error from response after update 

### ISSUE THREAD

**Issue by bunke** [agoalofalife/bpm-online#5]
When I'm execute update action with error, I've got handler:

object(agoalofalife\bpm\Handlers\XmlHandler)#43 (6) {
  ["response":"agoalofalife\bpm\Handlers\XmlHandler":private]=>
  object(SimpleXMLElement)#46 (3) {
    ["code"]=>
    string(1) "1"
    ["message"]=>
    string(45) "Элемент UsrDiagnosis не найден"
    ["innererror"]=>
    object(SimpleXMLElement)#41 (3) {
      ["message"]=>
      string(45) "Элемент UsrDiagnosis не найден"
      ["type"]=>
      string(38) "Terrasoft.Common.ItemNotFoundException"
....

method ->toArray() do not return response in this case

How can I parse response->message ? this field is private, can I write some getter?

**Comment by agoalofalife** [comment]
@bunke  
I don't use project, so I can't remember.
When I have time I will be able to help you.
or you can eliminate it yourself

**Comment by bunke** [comment]
Created pull request https://github.com/agoalofalife/bpm-online/pull/6

**Comment by agoalofalife** [comment]
add new realease v2.2.0

**Comment by bunke** [comment]
Updated composer.json https://github.com/agoalofalife/bpm-online/pull/7

**Comment by agoalofalife** [comment]
add new realease v2.2.1
